# Introduction

Tropical forests provide important ecosystem services at the global scale, such as biodiversity conservation and climate regulation [@Costanza1997], and at the local scale for people livelihood [@Anderson2006;@Jeannoda2007;@Gardner2014]. On the island of Madagascar, three types of tropical forests, covering about 15% of the country area, can be found: the moist forest in the East, the xerophytic forest in the South, and the dry forest in the West [@Humbert1955]. Among all the ecosystem services they provide, Malagasy forests are particularly important for the unique biodiversity they shelter, both in terms of species diversity and endemism in many taxonomic groups [@Goodman2005;@Brooks2006]. 

However, a large part of the original tropical forest is thought to have disappeared since the arrival of the humans on the island around 2000 years ago [@Green1990; @Harper2007; @Vieilledent2018], some studies advancing that 90% of the island was originally covered by forest [@Burns2016]. From 1950 to 2014, a loss of about 46% of the forest cover has been estimated [@Vieilledent2018], leading to an estimated extinction of 9% of the species between 1950 and 2000 in Madagascar [@Allnutt2008]. Common narrative attributes the deforestation to the extreme poverty of the country and subsistence farming through slash-and-burn agriculture [@Jarosz1993; @Scales2011; @Gardner2013]. About 81% of the population leave below the international poverty line of 1.25$\$$ per day in 2010 and more than 70% of the population of Madagascar, of 24 million people in 2015 [@WB2015], heavily rely on forests for their livelihood [@Anderson2006]. Moreover, Malagasy population is rapidly increasing, with population growing at a rate close to 3%.yr$-1$, thus doubling each 25 years.

To curb deforestation, several conservation and rural development programs have been implemented in Madagascar since the establishment of the first protected areas in 1927. The Madagascar Protected Area System (SAPM) has seen both an increase in the number of protected areas and an increase in the place taken by rural development programs to accompany conservation actions [@Virah2014]. Rural development programs aimed at alleviate poverty, increase agriculture productivity, education, health and local governance in the periphery of the protected areas [@Freudenberger2010]. Since 2003, Madagascar's protected area coverage expanded from 1.7 to 6.4 Mha (11% of the country area) [@Kremen2008; @Corson2014]. In parallel to the development of the SAPM, the REDD+ (Reducing Emissions from Deforestation and Forest Degradation) mechanism have emerged in Madagascar to avoid deforestation combining conservation and development actions [@Ebeling2008]. Five REDD+ pilot projects have been initiated since 2004 over a total of 1.76 Mha of forest [@Demaze2014]. 

Most of these actions were funded by the donor community, led by the USAID (United States Agency for International Development) and the World Bank [@Freudenberger2010]. The total funding of the National Environmental Action Program (NEAP) from 1990 to 2010 has been estimated at approximately \$450 million for environment activities, with another 50% for related development programs (e.g. agriculture and health interventions) [@Freudenberger2010]. Other bilateral donors (mainly Europe, France and Germany) have also funded specific socio-environmental projects (\$102 million on the period 2005--2011) [@CEPF2014]. The main international NGOs (WWF, CI, WCS) and international research centers (such as Cirad and IRD French research centers) also contributed significantly to the financial effort by providing their own resources to support conservation and development programs [@CEPF2014]. Regarding REDD+ activities, the private sector also provided substantial fundings. As an example, Air France supported the first phase of the PHCF REDD+ project (2008--2012) with \$5 million. Annually, this represent a rough estimate of about \$60 million per year from the donor community to fund environmental and related development activities in Madagascar (80% of the annual national budget) [@CEPF2014].

Despite all the efforts and money invested in conservation and development programs over the past 30 years (1985--2015), deforestation has not stopped on the island. Out of the 10.8 Mha of tropical forest in 1990, around 1.5 Mha (13% of the forest) has been deforested on the period 1990--2010 [@Harper2007;@Vieilledent2018], which corresponds to an average annual deforestation rate of 75,000 ha/yr (0.72%/yr). More worryingly, Madagascar has seen an acceleration of the deforestation recently [@Vieilledent2018]. Madagascar was the third country with the fastest acceleration of tree cover loss (+8.3% of ha/yr) on the period 2001--2014 (see @Hansen2013 and <http://ow.ly/RBbgw>). On the period 2010--2015, deforestation reached an average rate of 110,000 ha/yr (1.2%/yr). Forest cover in 2015 was estimated at 8.8 Mha [@Vieilledent2018; @Vieilledent2018data]. The conclusion is unfortunately rather clear: conservation and development programs since mid 1980s have failed to save Madagascar forests. It is therefore legitimate to wonder why such initiatives have not been successful and what could be the alternative solutions to stop deforestation. Also, the recent deforestation might be attributable to new factors, independent of local human activities, such as global climate change, cyclone and natural fires, which would imply conservation measures different to the ones used in the past. 

To try to answer these questions, we analysed more in depth the deforestation process in three study areas in the Menabe region (West of Madagascar). The study areas were located around three protected areas: the Menabe-Antimena New Protected Area (acronym MANAP in French), the Kirindy-Mite National Park (KMNP), and the Mikea National Park (MIKEA). These three protected areas are characteristic of the dry deciduous forest in Madagascar which is home to a unique biodiversity both in animals and plants (Fig. \@ref(fig:biodiversity)). Many species are endemic to the region such as the symbolic _Adansonia grandidieri_ of the Avenue of the Baobabs or _Microcebus berthae_, the smallest species of primate in the world. We derived historical forest cover change maps at 30 m resolution for the three study areas on the periods 1990--2010--2015. We validated these maps with field observations. To identify the main causes of the deforestation, we conducted local household and environmental stakeholder surveys. A much clearer scheme emerged from this analysis explaining why environmental actions currently fail at stopping deforestation. Finally, based on a spatial deforestation model, we predicted the likely future of the tropical dry forest in 2050 in the three study areas in the absence of any efficient solution to curb deforestation.

\newpage