# Materials and Methods

## Historical deforestation maps

We derived 30m cloud-free forest maps for Madagascar for the years 1990, 2000, 2010 and 2017 combining the 1990 and 2000 forest maps by @Harper2007 and the 2000-2017 tree percent cover map by @Hansen2013. On Harper's map, ~200,000 ha clouds are present over the ~4.2 million ha moist forest ecoregion (4.8% of clouds). To remove these clouds, we used the 2000 cloud-free tree percent cover map provided by @Hansen2013 (also at 30~m resolution) and we chose a threshold of 75% of tree cover to decide whether to replace cloud pixels with forest or non-forest pixels [@Achard2014]. We thus obtained a cloud-free year 2000 forest map for Madagascar. From this map, using tree cover loss data from 2000 to 2017 by @Hansen2013, we obtained cloud-free forest maps in 2010 and 2017 at 30~m resolution. Finally, we corrected the cloudy 1990 Harper forest map assuming that if forest was present in 2000, it was also present in 1990. Doing so, all clouds were removed and we obtained a cloud-free 1990 forest map for Madagascar. These maps are freely available at http:/bioscenemada.cirad.fr/forestmaps. We then used these national maps for our regional study around the Kirindy-Mite National Park (E: 43.67555, W: 44.35067, S: -21.36469, N: -20.50137, in decimal degrees) and the Menabe-Antimena New Protected Area (E: 44.20934, W: 44.8185, S: -20.3644, N: -19.55838, in decimal degrees). Field work was conducted during a ten days mission in June 2016 to verify the presence of the recent (2000-2010-2016) patches of deforestation in the two study areas. We validated the deforestation maps on this period and identified the main causes of deforestation in the two study areas. 

## Deforestation model

Following @Vieilledent2013, we considered two processes for modelling deforestation, a first one describing the intensity of deforestation (number of hectares of forest deforested each year) and a second one describing the location of the deforestation (spatial probability of deforestation). For the intensity of deforestation, we used two historical means at the study area level assuming a conservative scenario (S1) and a worst-case scenario (S2). The conservative scenario assumed a lower deforestation rate corresponding to the mean annual deforestation observed on the period 1990-2010. The worst-case scenario assumed a higher deforestation rate corresponding to the mean annual deforestation observed on the period 2000-2017, during which the deforestation has dramatically increased (Table 3). For the location of the deforestation, we estimated the parameters $\beta$ of a Binomial logistic regression linking the spatial probability of deforestation $\theta_i$ for forest pixel $i$ to a set of spatial explicative factors $X_i$ computed at the pixel level. To account for unexplained spatial variation in the probability of deforestation, we added a spatial random effect $\rho_{j(i)}$ at the level of the 10km resolution cell $j$ including the pixel $i$: $\text{logit}(\theta_i)=X_i\beta+\rho_{j(i)}$. To account for spatial autocorrelation, these spatial random effects were structured with a conditional autoregressive (CAR) model [@Besag1991] where $\rho_j$ depends on the values of $\rho_{j^{\prime}}$ for the neighbouring cells $j^{\prime}$. We used the deforestation data on the period 2000-2010 to fit the model. We used altitude, distance to forest edge, distance to main town, distance to main road, inclusion into a protected area and distance to past deforestation (period 1990-2000) as spatial explicative factors of the probability of deforestation [@Vieilledent2013]. These factors described the accessibility, the land policy and the historical deforestation of the forest. Model parameters were estimated in a Bayesian framework using the function `hSDM.binomial.iCAR()` from the hSDM `R` package [@Vieilledent2014]. The 10km spatial random effect estimates were interpolated at 1km using a bilinear interpolation. Using the results of the statistical model, we derived a map of the spatial probability of deforestation at 30m resolution for the year 2010 for Madagascar. The map is freely available at <https:/bioscenemada.cirad.fr/forestmaps.> We used this national map for our regional study (Fig. S1). To forecast the forest cover in 2050 for our two study areas, we removed the 2010 forest pixels with the highest probability of deforestation following the annual deforestation rate of the two intensity scenarios considered (conservative scenario S1 and worst-case scenario S2). To validate our projections, we computed the percentage of observed deforestation on the period 2010-2017 included in the predicted deforestation on the period 2010-2050.

## Surveys

During a ten day period in June 2016, we conducted surveys among local farmers and environmental stakeholders (Table 1) around the Kirindy-Mite National Park and the Menabe-Antimena New Protected Area. The objectives of the surveys were first to identify the causes of the deforestation and second to assess the efficiency of the conservation actions implemented by the NGOs in charge of the management of the protected areas, either Fanamby for MANPA or Madagascar National Parks for KMNP. Surveys were qualitative and included non-directive questions (no "yes-or-no" questions). Discussing with the _"Fokontany"_ chief at Lambokely, we also obtained rough population estimates on the period 2010-2015 for the two villages of Kirindy and Lambokely. The _"Fokontany"_ is a Malagasy administrative unit under the level of the township. Information from field surveys was cross-checked and complemented by a review of technical reports on the maize and peanut sectors in Madagascar [@Youssi2008; @MAEP2004; @ChanMouie2016; @Fauroux2000] and scientific studies on the deforestation process in south-east Madagascar [@Scales2011; @Zinner2014; @Fauroux2000; @Reau2002; @Casse2004; @Gardner2013].

\newpage