# Results

## Intensity and pattern of deforestation

Deforestation rates have continuously increased since 1990 for the MANAP and KMNP study areas (Tab. \@ref(tab:defor-rate)). After a decrease in 2000--2010, deforestation in the MIKEA study area has dramatically increased in 2010--2015 (Tab. \@ref(tab:defor-rate)). We estimated that 4,249 ha, 4,238 ha and 9,829 ha of forest have disappeared annually on the period 2010--2015 in the MANAP, KMNP, and MIKEA study areas, respectively. This corresponds to annual deforestation rates of 2.49--3.16%/yr. Deforestation has more than doubled on the period 2010--2015 compared to the period 2000--2010, for which deforestation was estimated at 0.66--0.87%/yr.

In the MANAP study area, large patches of deforestation associated to slash-and-burn agriculture were identified around the Kirindy and Lambokely villages and at the south of Belo-sur-Tsiribihina town (Fig. \@ref(fig:deforestation)a, label A).

In the KMNP study area, mosaic deforestation associated to slash-and-burn agriculture occurred outside the protected area, showing a relative effectiveness of the protected area to prevent deforestation (Fig. \@ref(fig:deforestation)b, label A). Much larger patches of deforestation have been observed on the two periods 2005--2010 and 2010--2015 on the east part of the protected area (Fig. \@ref(fig:deforestation)b, label B). These large patches of deforestation have been caused by the cyclone _Fanele_ that occured in January 2009 (Appendix 2) and which was followed by uncontrolled fires. Dispersed and small-scale deforestation has also been observed in the northern and western part of the park associated to illegal logging activities (Fig. \@ref(fig:deforestation)b, label C).

In the MIKEA study area, most of the deforestation was located at the north of the protected area (far from the Madagascar National Park office, which is located at the south of the study area) and was both due to slash and burn agriculture (Fig. \@ref(fig:deforestation)c, label A) and to uncontrolled fires following cyclone _Haruna_ which occurred in February 2013 (Fig. \@ref(fig:deforestation)c, label B and Appendix 2).

## Deforestation drivers

### Proximate causes of deforestation: slash-and-burn agriculture and uncontrolled fires

In the MANAP study area, the main cause of deforestation was the slash-and-burn agriculture (locally known as _"hatsake"_) for maize (_Zea mays_ (Linné)) and peanut (_Arachis hypogaea_ (Linné)) crop (Fig. \@ref(fig:causes)). The burning of forest provides nutrient rich ash and light for crops. It allows to expand cultivable areas and to optimize labor productivity as it directs fields towards areas with higher fertility and lower quantity of weeds, improving yields and reducing the necessary time for weeding. In the KMNP and MIKEA study areas, slash-and-burn agriculture was also identified as a cause of deforestation, but preferentially outside protected areas (Fig. \@ref(fig:deforestation)b-c, label A). 

Inside KMNP and MIKEA protected areas, uncontrolled fires (Fig. \@ref(fig:causes)) were the main cause of deforestation (Fig. \@ref(fig:deforestation)b-c, label B). People repeatedly set fire on former grasslands (called _"bozake"_) outside the protected area to obtain flush of green pasture for their livestock. When uncontrolled, fires can spread on large areas of forest and cross the boundaries of the protected area. In 2009, the cyclone named _Fanele_ (Appendix 2) impacted a large area of the forest in the Kirindy-Mite National Park leaving a lot of wood fuel on the ground. This has allowed uncontrolled fires to spread on large areas of the park in the years following the cyclone (Fig. \@ref(fig:deforestation)b, label B). These fires were hardly stopped with water and sand by the agents of the park with the help of local villagers. The same thing happened in the MIKEA study area after the cyclone named _Haruna_ in 2013 (Fig. \@ref(fig:deforestation)c, label B and Appendix 2). Cyclones also provide opportunities to local people to gain land other the forest. People can more difficulty be accused of destroying the forest and cyclone avoid the penible work of cutting down the trees before burning.

Illegal logging was also identified as a cause of forest degradation in the three study areas (Fig. \@ref(fig:deforestation)b, label C). Illegal logging is not a direct cause of deforestation but a forest without precious wood is more easily burnt than an intact forest, so that degradation usually precedes deforestation. Timbers (Fig. \@ref(fig:causes)) are mainly used for house and boat construction and sold in local markets in Belo-sur-Mer and Morondava towns. 

### Ultimate causes of deforestation

#### Demographic growth and migration

Population increase in Western Madagascar, associated to demographic growth and migration, have accentuated the pressure on forest. The population of Kirindy and Lambokely villages (Fig. \@ref(fig:deforestation)a) has been roughly multiplied by 5 between 2010 and 2015 (from about 600 to 3000 inhabitants for Kirindy and from about 1000 to 5000 for Lambokely). This was both due to demographic growth and migration. The demographic rate in Madagascar is close to 3%/yr [@Vieilledent2013] which means that the population doubles each 25 years on average. In Lambokely and Kirindy villages, the families we surveyed had all more than six children. Also the possibility of cropping cash crops have attracted many people from the south of Madagascar during the last years, in particular from the _Androy_ and _Atsimo-Atsinanana_ regions (South-East of Madagascar). First migrants arrived in the central Menabe to work in large agricultural concessions authorized by the French colonial government. Notably, many _Tandroy_ migrants have arrived in the 1960s and established near the Beroboka village (located between Kirindy and Lambokely villages) to work in the sisal (_Agave sisalana_ (Perrine, 1838)) plantation of the de Heaulme family which is now abandoned. Moreover, consecutive droughts reported in South-Eastern Madagascar resulted in severe famines there, that forced several thousand _Tandroy_ families to migrate to Western Madagascar in search for new farming land.

#### Cash crops and unregulated domestic market

Peanut (Fig. \@ref(fig:causes)) is cultivated as cash crop and is consumed as whole seeds or transformed into peanut oil. According to FAO and UN Comtrade statistics (Tab. \@ref(tab:faostat)), most of the production is at the destination of the domestic market. In Western Madagascar, Maize (Fig. \@ref(fig:causes)) is cultivated for auto-consumption (about 30% of the production) and as cash crop (70%). While a large part of the maize production in Western Madagascar have been exported through the ports of Morondava and Tulear during the successive maize booms in the 20th century [@Scales2011; @Fauroux2000], the production of maize seems to be presently mainly at the destination of the domestic market (Tab. \@ref(tab:faostat)). Some people we interviewed said that the maize production was sold to the Star company to brew the THB national beer. We computed that about 2,471 ha of maize crop are necessary to produce the annual volume of THB (Appendix 3). This is a small number compared to the 249,186 ha of maize harvested annually in Madagascar (Tab. \@ref(tab:faostat)). Other sources [@MAEP2004] indicate that maize is used for livestock (poultry and pigs) feeding in Madagascar. Peanut and maize are sold by farmers to resellers at the price of 1,400 Ariary (MGA) and 400 Ariary per kilogram, respectively. For 2016, the production for a household was of 1.6 T of peanut and 2.5 T of maize, thus providing an annual income of about 3.24 millions MGA. With the money earned from the sale of the maize and peanut harvest, farmers invest in zebu herd acquisition. Many intermediaries, such as storers, domestic transporters, resellers and exporters make large profits associated to the maize and peanut production connecting rural households to the domestic market. During our stay in the field in June 2016, which took place in the middle of the peanut harvest, we observed an uninterrupted parade of trucks arriving and leaving the villages of Lambokely and Kirindy.

#### Limits in the application of conservation policy

Forest clearance is illegal in Madagascar since 1987 (Décret n°87-143, 20 April 1987), even outside the protected areas. However, the law is not respected nor applied. Almost nobody is prosecuted for forest clearance. During our stay in the field, seven people were arrested for doing slash-and-burn agriculture but were relaxed a few days later. The political crisis of 2009, followed by several years of political instability, has reinforced this state of lawlessness. Moreover, authorities commonly have economic interests in not curbing deforestation as they are often involved in the trade associated with cash crops. Indeed, many politics in Madagascar are also business leaders. Regarding the structures in charge of the management of the protected areas, such as Fanamby and Madagascar National Parks NGOs, they have no legal enforcement powers which are retained by local Government agencies. Thus, their unique role concerning forest conservation in the field is limited to population awareness of the forest conservation issues, to inventory and monitor the biodiversity in the parks, and to organize patrols to discourage forest clearance or report offences. But in any case they have the right to arrest people or to draw up a report and decide on a fine. NGOs also engage people as conservation partners (then named _"polis ny ala"_) to try to make them stewards of their forest but they have practically no power and will difficulty report illegal acts from known neighbours or relatives.

## Projected deforestation

```{r validation}
p1 <- round(perc[1,2])
p2 <- round(perc[1,3])
p3 <- round(perc[2,2])
p4 <- round(perc[2,3])
p5 <- round(perc[3,2])
p6 <- round(perc[3,3])
```

Following the conservative scenario S1 (projecting 1990--2010 mean annual deforestation) and the worst-case scenario S2 (projecting 2000--2015 mean annual deforestation), we predicted that 36-67% of the forest present in 2000 will have disappeared in 2050 (Tab. \@ref(tab:forest-cover)). On the period 2000--2015, around 20% of the forest have already disappeared. Forest in 2050 should remain preferentially in the protected areas but deforestation should not stop at the boundaries of the parks (Fig \@ref(fig:scenarios)). The model predicted that deforestation in the future should occur close to places were deforestation occurred in the past, thus correctly simulating the contagious process of deforestation (Fig \@ref(fig:scenarios)). Deforestation is also more likely to occur at short distances to villages and roads and at the forest edge (Fig \@ref(fig:scenarios)). Forest fragmentation is also predicted to increase in association to deforestation (higher number of disconnected forest patches in Fig \@ref(fig:scenarios)). Most of the deforestation observed on the period 2010--2015 was included in the deforested area predicted by the model on the period 2010--2050 (`r p1`-`r p2`% for MANAP, `r p3`-`r p4`% for KMNP, and `r p5`-`r p6`% for MIKEA for scenarios S1 and S2, respectively), thus validating partly the predictions regarding the location of the future deforestation.

\newpage
