# Discussion

## Historical deforestation, projections and consequences on livelihoods, biodiversity and climate-change

For the three study areas, we have shown a strong increase of the annual deforestation rates on the period 1990--2015. This increase, also observed by @Scales2011 and @Zinner2014 in the region, clearly demonstrate the inefficiency of the recent environmental policies to reduce deforestation. In the absence of any efficient future policy to curb deforestation, we predicted a 36--59% forest loss on the period 2000--2050. This scenario, confirmed by the results of @Zinner2014, would be terrible for both local villagers in terms of livelihoods and at the global scale for biodiversity and carbon emissions. In term of loss of biodiversity, @Allnutt2008 estimated a 9% decrease in the number of species after a deforestation of 40% on the period 1950--2000. In our case, given a forest loss of 36--67%, we can assume that the biodiversity loss would be of the same order of magnitude on the period 2000--2050. Many species endemic to the region, such as _Hypogeomis antimena_, _Mungotictis decemlineata_, _Microcebus berthae_ and _Pyxis planicauda_ could experience a dramatic demise of their populations resulting in a rapid tailspin toward extinction. Dry forests sequester an average of 52 Mg/ha (1Mg=10$^6$g) [@Vieilledent2016]. Considering the predicted forest cover loss of 229,384--393,119 ha on the period 2010--2050 for the three study areas combined, deforestation would lead to emissions of 11.9--20.4 Tg (1Tg=10$^{12}$g) of carbon in the atmosphere, thus contributing significantly to climate change. 

## Deforestation is not associated directly to poverty but to unregulated market and bad governance

Our field observations and surveys indicated that a large part of the deforestation was attributable to slash-and-burn agriculture for cash crops (maize and peanut). The major part of the maize and peanut production is at the destination of the domestic market. 

Increase in area harvested for peanut crop is clearly associated to an increase in peanut exports toward the Asian market.

While a large part of the maize production in Western Madagascar have been exported through the ports of Morondava and Tulear during the successive maize booms in the 20th century [@Scales2011; @Fauroux2000], the production of maize seems to be presently mainly at the destination of the domestic market.

Area harvested for maize crop are relatively constant since 2000, and slightly decreasing since 2010.  

In particular, maize is used for livestock feeding. The annual household income we computed associated to the selling of cash crops (about 3.24 millions MGA) was relatively high compared to the estimated median household income of 2.02 millions MGA (Gallup World Poll from the Gallup Organization). With the money earned from the sale of the maize and peanut harvest, farmers invest in accumulating zebu herd [@Casse2004; @Reau2002]. Buying zebu herd is a way for farmers of saving money such as a bank would do it [@Reau2002]. In Madagascar, cattle also represent status, wealth, and cultural identity [@Hobbs2016]. In Western Madagascar, people's diet is mainly composed of manioc (_Manihot esculenta_ (Crantz)), wild and cultivated yams (_Dioscorea spp._), and maize [@Falola2015]. The main purpose of the slash-and-burn agriculture is thus not to obtain food for subsistence but to cultivate cash crop in order to invest in livestock acquisition and to secure new farming lands [@Fauroux2000]. In line with other studies [@Grandin1988; @Jarosz1993; @Scales2011; @Gardner2013], we underline that it would be over simplistic to reduce the causes of the deforestation to the poverty of local population. 

Of course, Malagasy farmers do not make large profits and do not harvest most of the benefits associated to the culture of maize and peanut. Many intermediaries, such as storers, domestic transporters, resellers, exporters and corrupt officials reap most of the profits. Foreign entrepreneurs (European and Chinese) as well as entrepreneurs from the Malagasy elite (including _"Karana"_, the descendants of Indo-Pakistani migrants) connect rural households to the domestic market. Field surveys reported that several officials in the army or with political responsibilities, who are at the same time businessmen or entrepreneurs, are involved in this trade. As a consequence, stopping deforestation would go against the economic interest of some people having decisional and political power in Madagascar. In previous studies, @Jarosz1993 and @Scales2011 have clearly shown how economic booms of agricultural commodities and policies have driven deforestation in Madagascar during French colonization. Nowadays, deforestation in central Menabe is driven by the increasing demand in maize and peanut on the domestic market and by the possibility of making economic profits in these sectors.

Slash-and-burn agriculture for cash crops and the economic profits are made possible by the non-application of the environmental law in Madagascar. Forest clearance is illegal in Madagascar since 1987 (Décret n°87-143, 20 April 1987). In the field, the agents of MNP and Fanamby have no legal enforcement powers to arrest offender even when apprehended. Under-resourced local Government agencies that retain such legal powers are generally corrupt and have a low technical capacity, making their actions virtually ineffective. As a consequence, illegal activities such as slash-and-burn agriculture or setting fire to open pastures continue in full sight of everyone. This situation has been accentuated by the political crisis of 2009-2012 in Madagascar [@Ploch2012]. Madagascar is a fragile State country [@TFP2016]. Common characteristics of a fragile State include a central Government so weak or ineffective that it has little practical control over much of its territory. Our study confirms that the deforestation problem in Madagascar is more a governance problem in a context of unregulated economy than an economic development problem. Interestingly, two global studies have recently shown that corruption [@Venter2016], overexploitation and agriculture (including crop farming and livestock farming) [@Maxwell2016] were responsible for a major part of the biodiversity loss, thus reflecting our results. 

## Enforcing law and controlling agricultural sector to stop deforestation in Western Madagascar

If we want to stop deforestation in western Madagascar, it seems necessary to rethink the conservation strategies we adopted during the last 30 years, which was based on extended the protected area network and alleviating poverty. One solution we see would be that national companies engage into ecological certification for agriculture commodities in Madagascar [@Laurance2010; @Kiker1997]. Relative to estimates of conservation costs in the developing world, it has been shown that existing levels of environmental aid are insufficient [@Miller2013]. If the amount of the environmental aid have to be increased, the targets have also to be redefined and improving governance in Madagascar should be considered a priority [@Smith2003]. Brazil, which have reduced by two third the Amazon deforestation on 2005--2011 compared to 1996--2005, is a good example to show that both law enforcement (enforcement of the Brazilian Forest code) and control of the agricultural sector (voluntary moratoriums by the soy bean and beef industries) are efficient ways to rapidly curb deforestation [@Boucher2013;@Nepstad2009]. This success, even if temporary, should inspire conservationists working in Madagascar and in other developing countries facing tropical deforestation in general.

Following the recent election of Andry Rajoelina as president of Madagascar, several researchers and conservationists have recently propose solutions to takle the decline in the rule of law in Madagascar [@Jones2019]. Among the solutions they propose, they suggest in particular to Tackle environmental crime and Invest in Madagascar's Protected Areas. Out study demonstrates that...

\newpage
